//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorAccount
    {
        public int administratorID { get; set; }
        public int OfficerID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string roll { get; set; }
    
        public virtual officer officer { get; set; }
    }
}
