//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class officer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public officer()
        {
            this.officerStayIns = new HashSet<officerStayIn>();
            this.OfficerWorkAs = new HashSet<OfficerWorkA>();
            this.AdministratorAccounts = new HashSet<AdministratorAccount>();
        }
    
        public int officerID { get; set; }
        public string rank { get; set; }
        public string citizinID { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string imageURL { get; set; }
        public System.DateTime AddedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<officerStayIn> officerStayIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficerWorkA> OfficerWorkAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdministratorAccount> AdministratorAccounts { get; set; }
    }
}
