//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficerWorkA
    {
        public int officerid { get; set; }
        public int jobid { get; set; }
        public Nullable<System.DateTime> since { get; set; }
        public Nullable<System.DateTime> until { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual officer officer { get; set; }
    }
}
