//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prisoner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prisoner()
        {
            this.prisonerSatyIns = new HashSet<prisonerSatyIn>();
            this.PrisonerWorkAs = new HashSet<PrisonerWorkA>();
            this.visits = new HashSet<visit>();
        }
    
        public int prisonerID { get; set; }
        public int adjudicationid { get; set; }
        public string citizinid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string imageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisonerSatyIn> prisonerSatyIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrisonerWorkA> PrisonerWorkAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visits { get; set; }
        public virtual Adjudication Adjudication { get; set; }
    }
}
