//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prisonerCell
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prisonerCell()
        {
            this.prisonerSatyIns = new HashSet<prisonerSatyIn>();
        }
    
        public int prisonerCellID { get; set; }
        public int capacity { get; set; }
        public string cellType { get; set; }
        public Nullable<double> area { get; set; }
        public string address { get; set; }
        public int availableCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prisonerSatyIn> prisonerSatyIns { get; set; }
    }
}
