//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jailOtomationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitTime
    {
        public System.DateTime dateOfVisit { get; set; }
        public Nullable<System.TimeSpan> VisitTime1 { get; set; }
        public Nullable<int> num { get; set; }
    }
}
